NAME =		rush-02

SRCS_DIR =	srcs
INCLS_DIR =	incls
OBJS_DIR =	objs

SRCS =		main.c

OBJS =		$(SRCS:.c=.o)

SRCS_FULL = $(addprefix $(SRCS_DIR)/, $(SRCS))
OBJS_FULL =	$(addprefix $(OBJS_DIR)/, $(OBJS))

CC =		gcc
CFLAGS =	-Wall -Werror -Wextra
